server:
    port: 8080
    
spring:
    devtools:
        restart:
            enabled: true
            
zuul:
  routes:
    orchestrator:
      sensitiveHeaders: Cookie,Set-Cookie
      path: /orchestrator/**
      strip-prefix: true
      url: http://localhost:8888
    rmit:
      sensitiveHeaders: Cookie,Set-Cookie
      path: /rmit-back/**
      strip-prefix: false
      url: http://localhost:9999
